{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.rbac.clusterWide }}ClusterRole{{ else }}Role{{ end }}
metadata:
  name: {{ include "mcp-ephemeral-k8s.fullname" . }}
  labels:
    {{- include "mcp-ephemeral-k8s.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
{{- end }}
